Repository minetest/irrlicht, pull requests merged in 2024-02, with the labels that each got.

#284 Ensure that absent bone names work
  CMakeLists.txt
  include/ISceneNode.h
  include/ISkinnedMesh.h
  include/IrrCompileConfig.h
  source/Irrlicht/CAnimatedMeshSceneNode.cpp
  source/Irrlicht/CB3DMeshFileLoader.cpp
  source/Irrlicht/CB3DMeshFileLoader.h
  source/Irrlicht/CBoneSceneNode.cpp
  source/Irrlicht/CBoneSceneNode.h
  source/Irrlicht/CSceneManager.cpp
  source/Irrlicht/CSkinnedMesh.cpp
  source/Irrlicht/CSkinnedMesh.h
  source/Irrlicht/CXMeshFileLoader.cpp
  source/Irrlicht/SB3DStructs.h
Labels: enhancement

#285 [SDL] Improve handling of IMEs
  source/Irrlicht/CIrrDeviceSDL.cpp
  source/Irrlicht/CIrrDeviceSDL.h
Labels: enhancement, One approval

#290 Upgrade actions in CI
  .github/workflows/build.yml
Labels: One approval

#291 CFileSystem: Fix signed integer conversion on MinGW
  source/Irrlicht/CFileSystem.cpp
Labels: bug

#294 Missing value_or() when printing std::optional
  source/Irrlicht/CB3DMeshFileLoader.cpp
Labels: bug
